---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

#  - name: update repository index
#    apt:
#      update_cache: yes


  - name: install apache2 and php package for Ubuntu
    tags: apache, apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
#      upgrade: yes
#      update_cache: yes
    when: ansible_distribution == "Ubuntu"
#  - name: add php support for apache
#    apt:
#      name: libapache2-mod-php
#      state: latest


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
         name: samba
         state: latest


